version: '3.8'

services:
  mqtt-service:
    build:
      context: .  # Đảm bảo context đúng để Dockerfile được sử dụng trong cùng thư mục
    container_name: mqtt-service
    image: mqtt-service:latest
    ports:
      - "8085:8085"
    networks:
      - ptit-net
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: small_kit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  ptit-net:
    driver: bridge
