version: '3.8'

services:
  mqtt-service:
    build:
      context: .  # Đảm bảo context đúng để Dockerfile được sử dụng trong cùng thư mục
    container_name: mqtt-service
    image: mqtt-service:latest
    ports:
      - "8085:8085"
    networks:
      - ptit-net
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

networks:
  ptit-net:
    driver: bridge
