server:
  port: ${PORT:8083}
  servlet:
    context-path: /mqtt

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 50000
      maximum-pool-size: 100
      max-lifetime: 1000000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
      file-size-threshold: 2KB

telegram:
  chatId: ${TELEGRAM_CHAT_ID:-100}
  apiToken: ${TELEGRAM_API_TOKEN:-}
debug: ${DEBUG:true}
async:
  config:
    core-pool-size: ${ASYNC_CORE_POOL_SIZE:3}

mqtt:
  broker:
    url: ${MQTT_BROKER_URL}
  client:
    id: mqtt-service
  topic: mqtt/# 
  username: hungtran
  password: hungtran

logging:
  level:
    org.springframework: INFO
