server:
  port: ${PORT:8081}
  servlet:
    context-path: /mqtt

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 50000
      maximum-pool-size: 100
      max-lifetime: 1000000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

mqtt:
  broker:
    url: ${MQTT_BROKER_URL}
  client:
    id: mqtt-service
  topic: mqtt/#

logging:
  level:
    org.springframework: INFO
